# Generated by Django 4.2.7 on 2023-12-29 02:16

from django.db import migrations, models
import jackhack.game


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=16)),
            ],
            bases=(jackhack.game.Game, models.Model),
        ),
    ]
