# Generated by Django 4.2.7 on 2024-01-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('jackhack_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
